/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as Meroviq360RouteImport } from './routes/meroviq-360'
import { Route as LaunchpadRouteImport } from './routes/launchpad'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsQaEstimatorRouteImport } from './routes/tools.qa-estimator'
import { Route as ToolsGrammarCorrectorRouteImport } from './routes/tools.grammar-corrector'
import { Route as ToolsFileConverterRouteImport } from './routes/tools.file-converter'
import { Route as ToolsDigitalSignatureRouteImport } from './routes/tools.digital-signature'
import { Route as ServicesMarketingRouteImport } from './routes/services.marketing'
import { Route as ServicesDevelopmentRouteImport } from './routes/services.development'
import { Route as ResourcesSalesforceCareerFaqRouteImport } from './routes/resources.salesforce-career-faq'
import { Route as ResourcesQaTesterFaqRouteImport } from './routes/resources.qa-tester-faq'
import { Route as ResourcesItProfessionalsFaqRouteImport } from './routes/resources.it-professionals-faq'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const Meroviq360Route = Meroviq360RouteImport.update({
  id: '/meroviq-360',
  path: '/meroviq-360',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchpadRoute = LaunchpadRouteImport.update({
  id: '/launchpad',
  path: '/launchpad',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsQaEstimatorRoute = ToolsQaEstimatorRouteImport.update({
  id: '/qa-estimator',
  path: '/qa-estimator',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsGrammarCorrectorRoute = ToolsGrammarCorrectorRouteImport.update({
  id: '/grammar-corrector',
  path: '/grammar-corrector',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsFileConverterRoute = ToolsFileConverterRouteImport.update({
  id: '/file-converter',
  path: '/file-converter',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsDigitalSignatureRoute = ToolsDigitalSignatureRouteImport.update({
  id: '/digital-signature',
  path: '/digital-signature',
  getParentRoute: () => ToolsRoute,
} as any)
const ServicesMarketingRoute = ServicesMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDevelopmentRoute = ServicesDevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => ServicesRoute,
} as any)
const ResourcesSalesforceCareerFaqRoute =
  ResourcesSalesforceCareerFaqRouteImport.update({
    id: '/salesforce-career-faq',
    path: '/salesforce-career-faq',
    getParentRoute: () => ResourcesRoute,
  } as any)
const ResourcesQaTesterFaqRoute = ResourcesQaTesterFaqRouteImport.update({
  id: '/qa-tester-faq',
  path: '/qa-tester-faq',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesItProfessionalsFaqRoute =
  ResourcesItProfessionalsFaqRouteImport.update({
    id: '/it-professionals-faq',
    path: '/it-professionals-faq',
    getParentRoute: () => ResourcesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/launchpad': typeof LaunchpadRoute
  '/meroviq-360': typeof Meroviq360Route
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools': typeof ToolsRouteWithChildren
  '/resources/it-professionals-faq': typeof ResourcesItProfessionalsFaqRoute
  '/resources/qa-tester-faq': typeof ResourcesQaTesterFaqRoute
  '/resources/salesforce-career-faq': typeof ResourcesSalesforceCareerFaqRoute
  '/services/development': typeof ServicesDevelopmentRoute
  '/services/marketing': typeof ServicesMarketingRoute
  '/tools/digital-signature': typeof ToolsDigitalSignatureRoute
  '/tools/file-converter': typeof ToolsFileConverterRoute
  '/tools/grammar-corrector': typeof ToolsGrammarCorrectorRoute
  '/tools/qa-estimator': typeof ToolsQaEstimatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/launchpad': typeof LaunchpadRoute
  '/meroviq-360': typeof Meroviq360Route
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools': typeof ToolsRouteWithChildren
  '/resources/it-professionals-faq': typeof ResourcesItProfessionalsFaqRoute
  '/resources/qa-tester-faq': typeof ResourcesQaTesterFaqRoute
  '/resources/salesforce-career-faq': typeof ResourcesSalesforceCareerFaqRoute
  '/services/development': typeof ServicesDevelopmentRoute
  '/services/marketing': typeof ServicesMarketingRoute
  '/tools/digital-signature': typeof ToolsDigitalSignatureRoute
  '/tools/file-converter': typeof ToolsFileConverterRoute
  '/tools/grammar-corrector': typeof ToolsGrammarCorrectorRoute
  '/tools/qa-estimator': typeof ToolsQaEstimatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/launchpad': typeof LaunchpadRoute
  '/meroviq-360': typeof Meroviq360Route
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools': typeof ToolsRouteWithChildren
  '/resources/it-professionals-faq': typeof ResourcesItProfessionalsFaqRoute
  '/resources/qa-tester-faq': typeof ResourcesQaTesterFaqRoute
  '/resources/salesforce-career-faq': typeof ResourcesSalesforceCareerFaqRoute
  '/services/development': typeof ServicesDevelopmentRoute
  '/services/marketing': typeof ServicesMarketingRoute
  '/tools/digital-signature': typeof ToolsDigitalSignatureRoute
  '/tools/file-converter': typeof ToolsFileConverterRoute
  '/tools/grammar-corrector': typeof ToolsGrammarCorrectorRoute
  '/tools/qa-estimator': typeof ToolsQaEstimatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/impact'
    | '/launchpad'
    | '/meroviq-360'
    | '/privacy'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/tools'
    | '/resources/it-professionals-faq'
    | '/resources/qa-tester-faq'
    | '/resources/salesforce-career-faq'
    | '/services/development'
    | '/services/marketing'
    | '/tools/digital-signature'
    | '/tools/file-converter'
    | '/tools/grammar-corrector'
    | '/tools/qa-estimator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/impact'
    | '/launchpad'
    | '/meroviq-360'
    | '/privacy'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/tools'
    | '/resources/it-professionals-faq'
    | '/resources/qa-tester-faq'
    | '/resources/salesforce-career-faq'
    | '/services/development'
    | '/services/marketing'
    | '/tools/digital-signature'
    | '/tools/file-converter'
    | '/tools/grammar-corrector'
    | '/tools/qa-estimator'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/impact'
    | '/launchpad'
    | '/meroviq-360'
    | '/privacy'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/tools'
    | '/resources/it-professionals-faq'
    | '/resources/qa-tester-faq'
    | '/resources/salesforce-career-faq'
    | '/services/development'
    | '/services/marketing'
    | '/tools/digital-signature'
    | '/tools/file-converter'
    | '/tools/grammar-corrector'
    | '/tools/qa-estimator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ImpactRoute: typeof ImpactRoute
  LaunchpadRoute: typeof LaunchpadRoute
  Meroviq360Route: typeof Meroviq360Route
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ToolsRoute: typeof ToolsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meroviq-360': {
      id: '/meroviq-360'
      path: '/meroviq-360'
      fullPath: '/meroviq-360'
      preLoaderRoute: typeof Meroviq360RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launchpad': {
      id: '/launchpad'
      path: '/launchpad'
      fullPath: '/launchpad'
      preLoaderRoute: typeof LaunchpadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/qa-estimator': {
      id: '/tools/qa-estimator'
      path: '/qa-estimator'
      fullPath: '/tools/qa-estimator'
      preLoaderRoute: typeof ToolsQaEstimatorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/grammar-corrector': {
      id: '/tools/grammar-corrector'
      path: '/grammar-corrector'
      fullPath: '/tools/grammar-corrector'
      preLoaderRoute: typeof ToolsGrammarCorrectorRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/file-converter': {
      id: '/tools/file-converter'
      path: '/file-converter'
      fullPath: '/tools/file-converter'
      preLoaderRoute: typeof ToolsFileConverterRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/digital-signature': {
      id: '/tools/digital-signature'
      path: '/digital-signature'
      fullPath: '/tools/digital-signature'
      preLoaderRoute: typeof ToolsDigitalSignatureRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/services/marketing': {
      id: '/services/marketing'
      path: '/marketing'
      fullPath: '/services/marketing'
      preLoaderRoute: typeof ServicesMarketingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/development': {
      id: '/services/development'
      path: '/development'
      fullPath: '/services/development'
      preLoaderRoute: typeof ServicesDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/resources/salesforce-career-faq': {
      id: '/resources/salesforce-career-faq'
      path: '/salesforce-career-faq'
      fullPath: '/resources/salesforce-career-faq'
      preLoaderRoute: typeof ResourcesSalesforceCareerFaqRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/qa-tester-faq': {
      id: '/resources/qa-tester-faq'
      path: '/qa-tester-faq'
      fullPath: '/resources/qa-tester-faq'
      preLoaderRoute: typeof ResourcesQaTesterFaqRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/it-professionals-faq': {
      id: '/resources/it-professionals-faq'
      path: '/it-professionals-faq'
      fullPath: '/resources/it-professionals-faq'
      preLoaderRoute: typeof ResourcesItProfessionalsFaqRouteImport
      parentRoute: typeof ResourcesRoute
    }
  }
}

interface ResourcesRouteChildren {
  ResourcesItProfessionalsFaqRoute: typeof ResourcesItProfessionalsFaqRoute
  ResourcesQaTesterFaqRoute: typeof ResourcesQaTesterFaqRoute
  ResourcesSalesforceCareerFaqRoute: typeof ResourcesSalesforceCareerFaqRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesItProfessionalsFaqRoute: ResourcesItProfessionalsFaqRoute,
  ResourcesQaTesterFaqRoute: ResourcesQaTesterFaqRoute,
  ResourcesSalesforceCareerFaqRoute: ResourcesSalesforceCareerFaqRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface ServicesRouteChildren {
  ServicesDevelopmentRoute: typeof ServicesDevelopmentRoute
  ServicesMarketingRoute: typeof ServicesMarketingRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesDevelopmentRoute: ServicesDevelopmentRoute,
  ServicesMarketingRoute: ServicesMarketingRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface ToolsRouteChildren {
  ToolsDigitalSignatureRoute: typeof ToolsDigitalSignatureRoute
  ToolsFileConverterRoute: typeof ToolsFileConverterRoute
  ToolsGrammarCorrectorRoute: typeof ToolsGrammarCorrectorRoute
  ToolsQaEstimatorRoute: typeof ToolsQaEstimatorRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsDigitalSignatureRoute: ToolsDigitalSignatureRoute,
  ToolsFileConverterRoute: ToolsFileConverterRoute,
  ToolsGrammarCorrectorRoute: ToolsGrammarCorrectorRoute,
  ToolsQaEstimatorRoute: ToolsQaEstimatorRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ImpactRoute: ImpactRoute,
  LaunchpadRoute: LaunchpadRoute,
  Meroviq360Route: Meroviq360Route,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ToolsRoute: ToolsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
